name: Planomasjid.org
favicon: null
layout_spectrum: 0.6102899350225925
typography_spectrum: 0.75389075698331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7414101471658796
  lightness: 0.9823732061777264
  saturation: 0.8863401787821203
  rhythmicContrast: 0.3150324267335236
purpose: []
